// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTw3IXJatG7p113TJzlxPNzOzAb8-1BYc',
    appId: '1:914298888508:web:4423b51597ea96b4903e39',
    messagingSenderId: '914298888508',
    projectId: 'instagram-8fafe',
    authDomain: 'instagram-8fafe.firebaseapp.com',
    storageBucket: 'instagram-8fafe.appspot.com',
    measurementId: 'G-X3T9KJJ3TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxA6wD9MWNCQth6CNImin3Aui1FwRpHPA',
    appId: '1:914298888508:android:fa9d20c5743671ae903e39',
    messagingSenderId: '914298888508',
    projectId: 'instagram-8fafe',
    storageBucket: 'instagram-8fafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRq-Hud8oZHJzJgAvsszX1tyNT_98BTAY',
    appId: '1:914298888508:ios:fdb5888ffc028581903e39',
    messagingSenderId: '914298888508',
    projectId: 'instagram-8fafe',
    storageBucket: 'instagram-8fafe.appspot.com',
    iosClientId: '914298888508-qe8v41u47bkbk8s7k3mevvvp79cm1gud.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
